name: Secure Scheduled Webhook Caller with Random Number

on:
  schedule:
    - cron: '0 14,18,23 * * *'

  
  workflow_dispatch:

jobs:
  call_webhook:
    runs-on: ubuntu-latest
    
    steps:
      - name: Call The Secure Webhook URL with Random Number
        run: |
          RANDOM_VALUE=$(( ($RANDOM % 7) + 1 ))

          curl -sf "${{ secrets.WEBHOOK_URL }}${RANDOM_VALUE}"
